Repository pressbooks/pressbooks, pull requests merged in 2018-04, with the labels that each got.

#1167 Fix: Keep multiselect order when using select2
  symbionts/custom-metadata/custom_metadata.php
  symbionts/custom-metadata/js/custom-metadata-manager.js
Labels: bug

#1169 Give super admins access to network themes/plugins; fix focus style
  assets/dist/mix-manifest.json
  assets/dist/styles/colors-pb.css
  assets/src/styles/colors-pb.scss
  inc/admin/laf/namespace.php
Labels: enhancement

#1171 Remove Creative Commons API-dependent test
  tests/test-licensing.php
Labels: enhancement

#1172 Blacklist taxonomies instead of whitelisting (known) allowed ones (fix #1095)
  inc/redirect/namespace.php
Labels: enhancement

#1175 Prevent slug collisions (fix #1174)
  inc/modules/export/htmlbook/class-htmlbook.php
  inc/modules/export/xhtml/class-xhtml11.php
Labels: enhancement

#1178 Bump minimum WordPress to 4.9.5 (fix #1176)
  README.md
  compatibility.php
  package.json
  readme.txt
  yarn.lock
Labels: dependencies

#1179 Improve requires so that other plugins can use them
  compatibility.php
  hooks-admin.php
  hooks.php
  requires-admin.php
  requires.php
Labels: enhancement

#1180 Add more specificity to web overrides for Custom CSS
  inc/modules/themeoptions/class-weboptions.php
Labels: enhancement

#1181 Add theme option for collapsing sections
  inc/modules/themeoptions/class-weboptions.php
Labels: enhancement

#1183 Add debug parameter to XHTML and HTMLBook URLs
  inc/modules/export/htmlbook/class-htmlbook.php
  inc/modules/export/xhtml/class-xhtml11.php
  tests/test-modules-export.php
Labels: enhancement

#1187 Make sure that collapse functionality is only present for supported themes
  inc/class-styles.php
  inc/modules/export/epub/class-epub201.php
  inc/modules/export/xhtml/class-xhtml11.php
  inc/modules/themeoptions/class-weboptions.php
  tests/test-styles.php
Labels: enhancement

#1188 Ignore SASS vars prefixed with _ in parseVariables method
  inc/class-sass.php
  tests/test-sass.php
Labels: enhancement

#1189 MVP: allow customization of educational textbox colours (fix #1182)
  assets/dist/mix-manifest.json
  assets/dist/scripts/theme-options.js
  assets/src/scripts/theme-options.js
  hooks-admin.php
  inc/admin/laf/namespace.php
  inc/modules/themeoptions/class-ebookoptions.php
  inc/modules/themeoptions/class-globaloptions.php
  inc/modules/themeoptions/class-pdfoptions.php
  inc/modules/themeoptions/class-weboptions.php
Labels: enhancement

#1191 Disable SSL verification in development environments
  inc/modules/export/epub/class-epub201.php
  inc/utility/namespace.php
Labels: enhancement

#1193 Table editor improvements
  inc/editor/namespace.php
  tests/test-editor.php
Labels: a11y, enhancement

#1194 Fix default color bug, add section headings, remove text colors
  inc/class-options.php
  inc/modules/themeoptions/class-ebookoptions.php
  inc/modules/themeoptions/class-globaloptions.php
  inc/modules/themeoptions/class-pdfoptions.php
  inc/modules/themeoptions/class-weboptions.php
  tests/test-options.php
Labels: enhancement

#1196 Add programatic login function
  inc/redirect/namespace.php
  pressbooks.php
  tests/test-redirect.php
Labels: enhancement

#1199 Add sidebar textbox menu items (fix pressbooks/buckram#66)
  assets/dist/mix-manifest.json
  assets/dist/scripts/textboxes.js
  assets/src/scripts/textboxes.js
  languages/tinymce.php
Labels: enhancement

#1200 Improve support for WP QuickLaTeX
  assets/dist/mix-manifest.json
  assets/dist/styles/pressbooks.css
  assets/src/styles/pressbooks.scss
  inc/admin/laf/namespace.php
  inc/admin/plugins/namespace.php
  inc/utility/namespace.php
  tests/test-admin-laf.php
Labels: enhancement

#1201 Replace Creative Commons API usage
  inc/class-licensing.php
  tests/test-licensing.php
Labels: enhancement

#1202 Use SVG images instead of spans (depends on pressbooks/buckram#98) (fix #1170)
  inc/class-licensing.php
  inc/modules/export/epub/class-epub201.php
  tests/test-licensing.php
Labels: enhancement

#1203 Add option for comparison with source (fix pressbooks/pressbooks-book#152)
  inc/modules/themeoptions/class-weboptions.php
  tests/test-options.php
  tests/test-themeoptions.php
Labels: enhancement
