Repository pressbooks/pressbooks, pull requests merged in 2018-02, with the labels that each got.

#1099 Compile pressbooks-book web stylesheet when using the Custom CSS theme
  inc/admin/fonts/namespace.php
  inc/class-styles.php
Labels: enhancement

#1110 Update composer packages to latest versions.
  composer.json
  composer.lock
Labels: dependencies

#1116 Move PB_PLUGIN_VERSION after compatibility check, use WP headers for version
  compatibility.php
  pressbooks.php
Labels: enhancement

#1115 Plugin Compatibility Checker
  assets/dist/mix-manifest.json
  assets/dist/styles/pressbooks.css
  assets/src/styles/pressbooks.scss
  hooks-admin.php
  inc/class-updates.php
  templates/admin/incompatible-plugins.blade.php
  tests/test-updates.php
Labels: enhancement

#1117 Don't clone sections with restrictive licenses
  inc/class-cloner.php
  inc/modules/import/api/class-api.php
  inc/modules/import/class-import.php
  tests/test-cloner.php
Labels: enhancement

#1119 Fix metadata importing over API
  inc/class-cloner.php
Labels: enhancement

#1118 Update Pressbooks CLI to 1.6.0
  composer.json
  composer.lock
Labels: dependencies, enhancement

#1120 Fix when Buckram is updated
  inc/class-styles.php
  tests/test-styles.php
Labels: enhancement

#1124 Remove pressbooks-publisher, fix broken activation hook.
  compatibility.php
  composer.json
  inc/class-activation.php
  pressbooks.php
Labels: bug
