Repository pressbooks/pressbooks, pull requests merged in 2018-06, with the labels that each got.

#1223 Update leafo/scssphp to 0.7.6
  composer.json
  composer.lock
Labels: dependencies

#1224 Ensure that classnames are output properly for EPUB TOC (fix pressbooks/pressbooks-asimov#32)
  inc/modules/export/epub/class-epub201.php
Labels: bug

#1210 Improve edu textbox markup, add sidebar textboxes (fix pressbooks/buckram#66)
  assets/dist/mix-manifest.json
  assets/dist/scripts/textboxes.js
  assets/src/scripts/cssanimations.js
  assets/src/scripts/post-visibility.js
  assets/src/scripts/search-and-replace.js
  assets/src/scripts/textboxes.js
  languages/tinymce.php
  yarn.lock
Labels: enhancement

#1227 Improve reverse_wpautop() function (fix #1225)
  inc/sanitize/namespace.php
  tests/test-sanitize.php
Labels: enhancement

#1226 Network admin menu changes
  assets/dist/mix-manifest.json
  assets/dist/scripts/table.js
  assets/dist/styles/colors-pb.css
  assets/dist/styles/pressbooks.css
  assets/src/styles/colors-pb.scss
  assets/src/styles/pressbooks.scss
  hooks-admin.php
  inc/admin/dashboard/namespace.php
  inc/admin/laf/namespace.php
  inc/utility/namespace.php
  tests/test-admin-dashboard.php
  tests/test-admin-delete-book.php
  tests/test-utility.php
Labels: enhancement

#1239 Add filter which allows public/private webbook settings to be hidden
  inc/admin/laf/namespace.php
  templates/admin/organize.php
Labels: enhancement

#1240 Docraptor in core (fixes #1238)
  .travis.yml
  composer.json
  composer.lock
  hooks-admin.php
  inc/admin/delete/class-book.php
  inc/modules/export/prince/class-docraptor.php
  inc/modules/export/prince/class-docraptorprint.php
  inc/modules/export/prince/class-filters.php
  inc/modules/searchandreplace/class-searchandreplace.php
  inc/shortcodes/footnotes/class-footnotes.php
  inc/shortcodes/generics/class-generics.php
  inc/shortcodes/wikipublisher/class-glyphs.php
  tests/test-container.php
  tests/test-l10n.php
  tests/test-modules-export.php
  tests/test-namespace.php
  tests/test-options.php
  tests/test-themelock.php
  tests/test-updates.php
Labels: enhancement

#1237 Use WP polyfills for is_countable() method
  compatibility.php
  inc/modules/export/class-export.php
  inc/modules/export/prince/class-pdf.php
  inc/modules/export/xhtml/class-xhtml11.php
  readme.txt
Labels: enhancement

#1236 Privacy policy management
  hooks-admin.php
  inc/admin/laf/namespace.php
  inc/admin/privacy/namespace.php
  requires-admin.php
  tests/test-admin-privacy.php
Labels: enhancement, work-in-progress

#1243 Hot patch coming through :(
  inc/image/namespace.php
Labels: bug

#1245 Fix #URL_FRAGMENT in `fixInternalLinks`
  inc/modules/export/htmlbook/class-htmlbook.php
  inc/modules/export/xhtml/class-xhtml11.php
Labels: bug

#1246 Change cron from `hourly` to `twicedaily` fixes #1242
  hooks-admin.php
  hooks.php
  inc/admin/privacy/namespace.php
  inc/class-privacy.php
  requires-admin.php
  tests/test-admin-privacy.php
  tests/test-namespace.php
  tests/test-privacy.php
Labels: enhancement
