Repository pressbooks/pressbooks, pull requests merged in 2018-07, with the labels that each got.

#1248 Match PrinceXML HTTP timeout to PHP's max_execution_time
  inc/modules/export/prince/class-docraptor.php
  inc/modules/export/prince/class-pdf.php
Labels: enhancement

#1249 Fix suppression of TOC part and chapter numbers for Buckram 1.0 themes
  inc/modules/themeoptions/class-pdfoptions.php
  tests/test-pdfoptions.php
Labels: bug

#1254 Only show warnings if both DocRaptor and Prince are missing dependencies (fix #1253)
  .travis.yml
  inc/modules/export/prince/class-filters.php
  templates/admin/export.php
Labels: bug

#1247 Iframes: Try embed instead.
  inc/interactive/class-content.php
  tests/test-interactive-content.php
Labels: enhancement

#1252 Use old textbox markup for themes which aren't built with Buckram >= 1.0
  assets/dist/mix-manifest.json
  assets/dist/scripts/post-visibility.js
  assets/dist/scripts/textboxes-legacy.js
  assets/dist/scripts/theme-lock.js
  assets/dist/scripts/theme-options.js
  assets/src/scripts/textboxes-legacy.js
  inc/editor/namespace.php
  webpack.mix.js
Labels: bug

#1258 Bump minimum WordPress to 4.9.7
  .travis.yml
  README.md
  compatibility.php
  inc/image/namespace.php
  readme.txt
  tests/test-privacy.php
Labels: enhancement

#1260 Import part content (fix #1259)
  inc/modules/import/wordpress/class-wxr.php
Labels: bug

#1264 License
  inc/class-licensing.php
  tests/test-licensing.php
Labels: enhancement

#1270 Prepare 5.4.1 release
  languages/_pressbooks.pot
  package.json
  pressbooks.php
  readme.txt
  yarn.lock
Labels: enhancement

#1263 Swap coding standards
  compatibility.php
  composer.json
  composer.lock
  hooks-admin.php
  hooks.php
  inc/admin/analytics/namespace.php
  inc/admin/branding/namespace.php
  inc/admin/class-catalog-list-table.php
  inc/admin/dashboard/namespace.php
  inc/admin/diagnostics/namespace.php
  inc/admin/laf/namespace.php
  inc/admin/metaboxes/namespace.php
  inc/admin/network/class-sharingandprivacyoptions.php
  inc/admin/networkmanagers/namespace.php
  inc/api/endpoints/controller/class-metadata.php
  inc/api/endpoints/controller/class-sectionmetadata.php
  inc/api/namespace.php
  inc/class-book.php
  inc/class-catalog.php
  inc/class-cloner.php
  inc/class-contributors.php
  inc/class-metadata.php
  inc/class-styles.php
  inc/class-taxonomy.php
  inc/editor/namespace.php
  inc/image/namespace.php
  inc/interactive/class-content.php
  inc/metadata/namespace.php
  inc/modules/export/class-export.php
  inc/modules/export/epub/class-epub201.php
  inc/modules/export/epub/class-epub3.php
  inc/modules/export/epub/templates/epub201/html.php
  inc/modules/export/epub/templates/epub201/opf.php
  inc/modules/export/epub/templates/epub3/html.php
  inc/modules/export/epub/templates/epub3/opf.php
  inc/modules/export/epub/templates/epub3/toc.php
  inc/modules/export/htmlbook/class-htmlbook.php
  inc/modules/export/odt/class-odt.php
  inc/modules/export/prince/class-pdf.php
  inc/modules/export/xhtml/class-xhtml11.php
  inc/modules/import/class-import.php
  inc/modules/import/epub/class-epub201.php
  inc/modules/import/odf/class-odt.php
  inc/modules/import/ooxml/class-docx.php
  inc/modules/import/wordpress/class-wxr.php
  inc/modules/searchandreplace/class-search.php
  inc/modules/searchandreplace/class-searchandreplace.php
  inc/modules/searchandreplace/types/class-content.php
  inc/modules/themeoptions/class-ebookoptions.php
  inc/modules/themeoptions/class-globaloptions.php
  inc/modules/themeoptions/class-pdfoptions.php
  inc/modules/themeoptions/class-themeoptions.php
  inc/modules/themeoptions/class-weboptions.php
  inc/posttype/namespace.php
  inc/registration/namespace.php
  phpcs.ruleset.xml
Labels: enhancement

#1273 Fix highlight colour in styles dropdown (resolves #1250)
  assets/dist/mix-manifest.json
  assets/dist/styles/colors-pb.css
  assets/src/styles/colors-pb.scss
Labels: a11y, enhancement

#1274 Fix EPUB section subtitle and author order (resolves #1271)
  inc/modules/export/epub/class-epub201.php
Labels: enhancement

#1275 Allow super admins to debug styles at format endpoint (resolves #1272)
  inc/modules/export/htmlbook/class-htmlbook.php
  inc/modules/export/xhtml/class-xhtml11.php
Labels: enhancement

#1277 Retain original slug during WXR import (resolve #1276)
  inc/modules/import/wordpress/class-wxr.php
Labels: enhancement

#1290 Only force test mode in development (fixes #1289)
  inc/modules/export/prince/class-docraptor.php
  inc/modules/export/prince/class-pdf.php
Labels: enhancement

#1294 When Buckram is updated, rebuild the editor stylesheet (fix #1278)
  inc/class-styles.php
Labels: enhancement

#1293 Enable TablePress for EPUB/MOBI
  hooks-admin.php
  hooks.php
  inc/admin/diagnostics/namespace.php
  inc/admin/plugins/namespace.php
  inc/shortcodes/class-tablepress.php
Labels: enhancement

#1287 Attribution
  hooks-admin.php
  hooks.php
  inc/admin/attachments/namespace.php
  inc/media/namespace.php
  inc/modules/themeoptions/class-globaloptions.php
  inc/posttype/namespace.php
  inc/shortcodes/attributions/class-attachments.php
  inc/shortcodes/footnotes/class-footnotes.php
  requires-admin.php
  tests/test-admin-attachments.php
  tests/test-media.php
  tests/test-shortcodes-attributions-attachments.php
Labels: enhancement

#1300 Ensure that contributor taxonomies are registered when needed
  inc/class-contributors.php
Labels: enhancement
