Repository pressbooks/pressbooks, pull requests merged in 2019-02, with the labels that each got.

#1576 H5P Cloning (fixes #1529)
  assets/dist/mix-manifest.json
  assets/dist/scripts/blockui.js
  assets/dist/scripts/isotope.js
  assets/dist/scripts/js-cookie.js
  assets/dist/scripts/matchheight.js
  assets/dist/scripts/select2.js
  assets/dist/scripts/sidr.js
  assets/dist/scripts/sticky.js
  assets/dist/scripts/table.js
  hooks-admin.php
  hooks.php
  inc/admin/laf/namespace.php
  inc/api/namespace.php
  inc/class-eventstreams.php
  inc/class-htmlparser.php
  inc/class-taxonomy.php
  inc/class-updates.php
  inc/cloner/class-cloner.php
  inc/cloner/class-downloads.php
  inc/editor/namespace.php
  inc/entities/cloner/class-h5p.php
  inc/interactive/class-content.php
  inc/interactive/class-h5p.php
  inc/modules/export/class-export.php
  inc/modules/export/namespace.php
  inc/modules/import/api/class-api.php
  inc/modules/import/class-import.php
  inc/modules/import/wordpress/class-downloads.php
  inc/modules/import/wordpress/class-wxr.php
  inc/sanitize/namespace.php
  inc/shortcodes/glossary/class-glossary.php
  package-lock.json
  tests/test-cloner.php
  tests/test-integrations.php
  tests/test-interactive-content.php
  tests/test-interactive-h5p.php
  tests/test-utility-percentageyield.php
Labels: enhancement

#1580 Remove leftover, half-done, preview code.
  inc/class-book.php
  inc/modules/export/class-export.php
  inc/modules/export/htmlbook/class-htmlbook.php
  inc/modules/export/odt/class-odt.php
  inc/modules/export/prince/class-pdf.php
  inc/modules/export/xhtml/class-xhtml11.php
Labels: enhancement

#1585 Export tweaks (fixes #1525)
  assets/dist/mix-manifest.json
  assets/dist/scripts/export.js
  assets/src/scripts/export.js
  inc/admin/laf/namespace.php
  inc/modules/export/class-table.php
  templates/admin/export.blade.php
  tests/test-modules-export-table.php
Labels: enhancement

#1586 Fix: Sometimes H5P cloning will fail and we can't do anything (fixes #1529)
  inc/cloner/class-cloner.php
  inc/cloner/class-downloads.php
  inc/interactive/class-h5p.php
  tests/test-interactive-h5p.php
Labels: enhancement

#1587 Fix SSE race condition
  inc/class-eventstreams.php
  tests/test-eventstreams.php
Labels: enhancement

#1589 Event streaming tweaks (fixes #1282)
  assets/dist/mix-manifest.json
  assets/dist/scripts/anchor.js
  assets/dist/scripts/cloner.js
  assets/dist/scripts/covergenerator.js
  assets/dist/scripts/export.js
  assets/dist/scripts/import.js
  assets/dist/styles/cloner.css
  assets/dist/styles/export.css
  assets/dist/styles/pressbooks.css
  assets/src/scripts/cloner.js
  assets/src/scripts/covergenerator.js
  assets/src/scripts/export.js
  assets/src/scripts/import.js
  assets/src/scripts/utils/displayNotice.js
  assets/src/scripts/utils/pad.js
  assets/src/scripts/utils/resetClock.js
  assets/src/scripts/utils/startClock.js
  assets/src/styles/cloner.scss
  assets/src/styles/export.scss
  assets/src/styles/pressbooks.scss
  inc/admin/covergenerator/namespace.php
  inc/admin/laf/namespace.php
  inc/modules/export/class-export.php
  inc/modules/export/class-table.php
  inc/modules/export/epub/class-epub201.php
  inc/modules/export/namespace.php
  templates/admin/cloner.php
  templates/admin/covergenerator.php
  templates/admin/export.blade.php
  templates/admin/export.php
  templates/admin/import.php
  tests/test-admin-laf.php
  tests/test-modules-export.php
  webpack.mix.js
Labels: enhancement, work-in-progress

#1592 Use Luther for legacy theme testing
  bin/install-wp-tests.sh
  tests/test-admin-fonts.php
  tests/test-covergenerator-generator.php
  tests/test-modules-export-export.php
  tests/test-pdfoptions.php
  tests/test-styles.php
Labels: enhancement

#1594 Add get_section_information() and add_json_ld_metadata() functions
  inc/api/endpoints/controller/class-sectionmetadata.php
  inc/metadata/namespace.php
  tests/test-metadata.php
Labels: enhancement

#1593 Fix: Media fallback hyperlinks (PDF)
  inc/modules/export/epub/class-epub201.php
  inc/modules/export/htmlbook/class-htmlbook.php
  inc/modules/export/xhtml/class-xhtml11.php
  tests/test-book.php
  tests/test-modules-export-export.php
  tests/utils-trait.php
Labels: bug

#1595 Add \Pressbooks\Metadata\add_citation_metadata() (fix pressbooks/pressbooks-book#435)
  functions.php
  inc/metadata/namespace.php
  tests/test-metadata.php
Labels: enhancement

#1597 Disable bulk actions if all files are pinned
  assets/dist/mix-manifest.json
  assets/dist/scripts/export.js
  assets/src/scripts/export.js
Labels: enhancement

#1598 Refine progress bar text
  inc/admin/covergenerator/namespace.php
  inc/cloner/class-cloner.php
  inc/covergenerator/class-generator.php
  inc/modules/export/class-export.php
  inc/modules/export/epub/class-epub201.php
  inc/modules/export/epub/class-epub3.php
  inc/modules/export/xhtml/class-xhtml11.php
  inc/modules/import/api/class-api.php
  inc/modules/import/class-import.php
  inc/modules/import/epub/class-epub201.php
Labels: enhancement

#1596 Fix: Wrong parameters for Exception
  inc/covergenerator/class-docraptorjpg.php
  inc/covergenerator/class-isbn.php
  inc/covergenerator/class-sku.php
Labels: bug

#1600 Handle weird usernames in Network Managers table
  inc/admin/class-network-managers-list-table.php
  tests/test-admin-networkmanagers-list-table.php
Labels: enhancement

#1604 Fix inaccurate API,EPUB import counts (fix #1599)
  inc/modules/import/api/class-api.php
  inc/modules/import/epub/class-epub201.php
  inc/utility/class-percentageyield.php
  tests/test-utility-percentageyield.php
Labels: enhancement

#1605 Refactored EPUB,API Imports To Count Totals Correctly
  inc/modules/import/api/class-api.php
  inc/modules/import/epub/class-epub201.php
Labels: enhancement

#1611 Fix missing user messages (pb_notice) when something goes wrong with H5P cloning
  inc/cloner/class-cloner.php
  inc/covergenerator/class-generator.php
  inc/modules/export/class-export.php
  inc/modules/export/class-exportgenerator.php
  inc/modules/export/epub/class-epub201.php
  inc/modules/export/epub/class-epub3.php
  inc/modules/export/xhtml/class-xhtml11.php
  inc/modules/import/class-import.php
  inc/modules/import/class-importgenerator.php
  inc/modules/import/epub/class-epub201.php
  inc/namespace.php
  inc/utility/class-percentageyield.php
  tests/test-admin-laf.php
Labels: enhancement

#1612 Fix PHP Notices (E_NOTICE) when cloning H5P
  inc/cloner/class-cloner.php
  inc/cloner/class-downloads.php
Labels: enhancement

#1608 Compatibility with WordPress 5.1 (Fix #1552)
  .travis.yml
  compatibility.php
  inc/class-activation.php
  inc/class-taxonomy.php
  readme.txt
  tests/test-activation.php
Labels: enhancement

#1614 Fix: Notice: Undefined index: pb_cover_image
  inc/class-catalog.php
Labels: bug
