Repository pressbooks/pressbooks, pull requests merged in 2025-08, with the labels that each got.

#4063 feat: replace @pressbooks/multiselect with @pressbooks/select
  assets/dist/mix-manifest.json
  assets/dist/scripts/pressbooks-reorderable-multiselect.js
  assets/dist/scripts/pressbooks-select.js
  assets/dist/scripts/pressbooks-select.js.LICENSE.txt
  assets/dist/styles/metadata.css
  assets/dist/styles/pressbooks.css
  assets/src/styles/metadata.scss
  inc/admin/laf/namespace.php
  inc/modules/themeoptions/class-globaloptions.php
  package-lock.json
  package.json
  templates/metaboxes/fields/select.blade.php
  webpack.mix.js
Labels: a11y

#4101 fix: allow spans with lang attributes in section titles
  inc/sanitize/namespace.php
  tests/test-sanitize.php
Labels: enhancement, a11y, accessible content

#4159 chore(dev): release 6.31.3
  .release-please-manifest.json
  CHANGELOG.md
  README.md
  pressbooks.php
Labels: autorelease: pending
