Repository pressbooks/pressbooks, pull requests merged in 2025-03, with the labels that each got.

#3935 chore(dev): release 6.22.4
  .release-please-manifest.json
  CHANGELOG.md
  README.md
  pressbooks.php
Labels: autorelease: pending

#3961 fix: resolve bug with taxonomy terms that use non-latin characters
  inc/admin/fields/class-taxonomyreorderablemultiselect.php
  inc/admin/fields/class-taxonomyselect.php
Labels: bug

#3962 fix(deps): update @pressbooks/reorderable-multiselect
  assets/dist/mix-manifest.json
  assets/dist/scripts/alpine.min.js
  assets/dist/scripts/instantsearch.production.min.js
  assets/dist/scripts/pressbooks-reorderable-multiselect.js
  assets/dist/styles/pressbooks.css
  package-lock.json
  package.json
Labels: a11y, dependencies, javascript

#3966 fix: properly label checkboxes on export page
  inc/modules/export/class-table.php
Labels: bug, a11y

#3965 fix: ensure that top nav items are accessible in mobile
  assets/dist/mix-manifest.json
  assets/dist/styles/pressbooks.css
  assets/src/styles/admin.scss
Labels: a11y

#3942 chore(dev): release 6.23.0
  .release-please-manifest.json
  CHANGELOG.md
  README.md
  pressbooks.php
Labels: autorelease: pending

#3970 chore(dev): release 6.23.1
  .release-please-manifest.json
  CHANGELOG.md
  README.md
  pressbooks.php
Labels: autorelease: pending
